name: Apk Diff

on: [pull_request]

jobs:
  # Checkout master branch and build the APK
  build-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build Master APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-master.apk

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build PR APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-pr.apk

      - name: Execute Diffuse
        run: ./diffuse diff apk/app-master.apk apk/app-pr.apk > diff_summary.txt
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: summary
          path: diff_summary.txt