name: Apk Diff
on: [pull_request]
jobs:
  # Checkout master branch and build the APK
  build-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: Build Master APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk build/app-master.apk
      # Checkout PR branch and build the APK
      - uses: actions/checkout@v1
      - name: Build PR APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk build/app-pr.apk
      - name: Execute Diffuse
        run: ./diffuse diff build/app-master.apk build/app-pr.apk