name: Apk Diff

on: [pull_request]

jobs:
  # Checkout master branch and build the APK
  build-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build Master APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-master.apk

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build PR APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-pr.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: |
            app/build/outputs/apk/debug/app-master.apk
            app/build/outputs/apk/debug/app-pr.apk

      - name: Download APKs
        uses: actions/download-artifact@v2
        with:
          name: apks
          path: apks
      - name: Display structure of downloaded files
        run: ls -R
      - name: Execute Diffuse
        run: ./diffuse diff ./apks/app-master.apk ./apks/app-pr.apk > diff_summary.txt
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: summary
          path: diff_summary.txt
