name: Apk Diff
on: [pull_request]
jobs:
  # Checkout master branch and build the APK
  build-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Build Master APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-master.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-master.apk

      - name: Checkout
      - uses: actions/checkout@v2
      - name: Build PR APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-pr.apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-pr.apk

      - name: Download APKs
        uses: actions/download-artifact@v2
        with:
          name: apk
      - uses: microsoft/android-app-size-diff@v0.27
        name: Run APK size comparision
        with:
          baseAppPath: apk/app-master.apk
          targetAppPath: apk/app-pr.apk
          summaryOutputPath: summary.md
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: summary
          path: summary.md
